-- ============================================================================
-- Warehouse Intelligence Platform — Supabase PostgreSQL Schema & Seed Script
-- Run this entire script in your Supabase SQL Editor (Dashboard -> SQL Editor)
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Organizations
CREATE TABLE IF NOT EXISTS organizations (
    id VARCHAR PRIMARY KEY,
    name VARCHAR NOT NULL,
    subscription_tier VARCHAR DEFAULT 'ENTERPRISE',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Facilities
CREATE TABLE IF NOT EXISTS facilities (
    id VARCHAR PRIMARY KEY,
    organization_id VARCHAR REFERENCES organizations(id),
    name VARCHAR NOT NULL,
    location VARCHAR,
    timezone VARCHAR DEFAULT 'Asia/Kolkata',
    status VARCHAR DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Users
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR PRIMARY KEY,
    organization_id VARCHAR REFERENCES organizations(id),
    facility_id VARCHAR REFERENCES facilities(id),
    email VARCHAR UNIQUE NOT NULL,
    hashed_password VARCHAR NOT NULL,
    full_name VARCHAR NOT NULL,
    role VARCHAR NOT NULL DEFAULT 'SUPERVISOR',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Loading Bays
CREATE TABLE IF NOT EXISTS loading_bays (
    id VARCHAR PRIMARY KEY,
    facility_id VARCHAR REFERENCES facilities(id),
    name VARCHAR NOT NULL,
    code VARCHAR NOT NULL,
    status VARCHAR DEFAULT 'Operational',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Cameras
CREATE TABLE IF NOT EXISTS cameras (
    id VARCHAR PRIMARY KEY,
    loading_bay_id VARCHAR REFERENCES loading_bays(id),
    name VARCHAR NOT NULL,
    camera_code VARCHAR NOT NULL,
    source_type VARCHAR DEFAULT 'RTSP',
    stream_url VARCHAR,
    status VARCHAR DEFAULT 'ONLINE',
    last_seen_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. Safety Rules
CREATE TABLE IF NOT EXISTS safety_rules (
    id VARCHAR PRIMARY KEY,
    facility_id VARCHAR REFERENCES facilities(id),
    behaviour_type VARCHAR NOT NULL,
    max_allowed_per_hour INTEGER DEFAULT 5,
    severity_weight FLOAT DEFAULT 1.0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. Videos
CREATE TABLE IF NOT EXISTS videos (
    video_id VARCHAR PRIMARY KEY,
    camera_id VARCHAR,
    filename VARCHAR NOT NULL,
    duration FLOAT DEFAULT 0.0,
    fps FLOAT DEFAULT 30.0,
    width INTEGER DEFAULT 1920,
    height INTEGER DEFAULT 1080,
    frame_count INTEGER DEFAULT 0,
    status VARCHAR DEFAULT 'processed',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 8. Events
CREATE TABLE IF NOT EXISTS events (
    event_id VARCHAR PRIMARY KEY,
    organization_id VARCHAR,
    facility_id VARCHAR,
    video_id VARCHAR,
    timestamp FLOAT NOT NULL,
    timestamp_seconds FLOAT DEFAULT 0.0,
    camera_id VARCHAR,
    bay_id VARCHAR,
    object_id INTEGER DEFAULT 1,
    behaviour VARCHAR NOT NULL,
    risk_level VARCHAR NOT NULL,
    risk_score FLOAT NOT NULL,
    description TEXT,
    reason TEXT,
    recommended_action TEXT,
    evidence_frame VARCHAR,
    video_reference VARCHAR,
    status VARCHAR DEFAULT 'UNRESOLVED',
    acknowledged_by VARCHAR,
    dispatched_to VARCHAR,
    dispatch_notes TEXT,
    provenance_type VARCHAR DEFAULT 'REAL_INFERENCE',
    environment VARCHAR DEFAULT 'PRODUCTION_PROTOTYPE',
    confidence FLOAT DEFAULT 0.94,
    model_name VARCHAR DEFAULT 'YOLO11s',
    model_version VARCHAR DEFAULT 'v1.4.2-tensorrt',
    is_demo_data BOOLEAN DEFAULT FALSE,
    is_test_data BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 9. Risk Assessments
CREATE TABLE IF NOT EXISTS risk_assessments (
    id VARCHAR PRIMARY KEY,
    event_id VARCHAR,
    behaviour_observation_id VARCHAR,
    risk_level VARCHAR NOT NULL,
    risk_score FLOAT NOT NULL,
    confidence FLOAT DEFAULT 0.94,
    reason TEXT,
    risk_factors_json TEXT,
    model_version VARCHAR DEFAULT 'warehouse-risk-v1.4',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 10. Model Runs Telemetry
CREATE TABLE IF NOT EXISTS model_runs (
    id VARCHAR PRIMARY KEY,
    model_name VARCHAR NOT NULL,
    model_version VARCHAR NOT NULL,
    device VARCHAR DEFAULT 'cuda',
    fps FLOAT DEFAULT 89.4,
    latency_ms FLOAT DEFAULT 11.2,
    confidence_threshold FLOAT DEFAULT 0.45,
    started_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR DEFAULT 'RUNNING'
);

-- ============================================================================
-- DATA INGESTION & CANONICAL SEED RECORDS
-- ============================================================================

-- Ingesting 1 records into organizations
INSERT INTO organizations (id, name, created_at, updated_at) VALUES ('ORG-001', 'Acme Logistics Global', '2026-09-09 06:13:30.700037', '2026-09-09 06:13:30.701243') ON CONFLICT (id) DO NOTHING;

-- Ingesting 2 records into facilities
INSERT INTO facilities (id, organization_id, name, location, timezone, status, created_at) VALUES ('FAC-001', 'ORG-001', 'Bengaluru Distribution Center', 'Building A - Dock Bay 4, Peenya Industrial Area', 'Asia/Kolkata', 'ACTIVE', '2026-09-09 06:13:30.711899') ON CONFLICT (id) DO NOTHING;
INSERT INTO facilities (id, organization_id, name, location, timezone, status, created_at) VALUES ('FAC-002', 'ORG-001', 'Mumbai Logistics Hub', 'Bhiwandi Dock Yard 09, Mumbai', 'Asia/Kolkata', 'ACTIVE', '2026-09-09 06:13:30.722353') ON CONFLICT (id) DO NOTHING;

-- Ingesting 3 records into users
INSERT INTO users (id, organization_id, email, hashed_password, full_name, role, facility_id, created_at, updated_at) VALUES ('user-admin-01', 'ORG-001', 'admin@wms-intel.io', 'pbkdf2_sha256$100000$0ede46d436302a37f37303f207d7fc4c$af9c51691b74bb95fbced0fcf5d5e36f08ff72b063fdd235be58115988eae40a', 'System Administrator', 'ADMIN', 'FAC-001', '2026-09-09 06:13:30.860573', '2026-09-09 17:59:45.838321') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, organization_id, email, hashed_password, full_name, role, facility_id, created_at, updated_at) VALUES ('user-sup-01', 'ORG-001', 'supervisor@wms-intel.io', 'pbkdf2_sha256$100000$4bc34edf5e3c5f49af09144404b132a6$bfd95c75a3ceb3bda1e7284daa5f68d2cdf317dc9c20fd4aa723e2b11c1df4b1', 'Dock Supervisor', 'SUPERVISOR', 'FAC-001', '2026-09-09 06:13:30.942543', '2026-09-09 17:59:45.838328') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, organization_id, email, hashed_password, full_name, role, facility_id, created_at, updated_at) VALUES ('user-op-01', 'ORG-001', 'operator@wms-intel.io', 'pbkdf2_sha256$100000$17cbb22fdd75f4550b1e25d2b333f1b4$33462ce8a42bfd4d9c4e4f765bc3e002be979ac5abc5923747b0441730a83f5d', 'Bay Operator', 'OPERATOR', 'FAC-001', '2026-09-09 06:13:31.023671', '2026-09-09 17:59:45.838326') ON CONFLICT (id) DO NOTHING;

-- Ingesting 6 records into loading_bays
INSERT INTO loading_bays (id, facility_id, name, code, status, created_at) VALUES ('BAY-01', 'FAC-001', 'Loading Bay 01', 'BAY-01-EXP', 'Operational', '2026-09-09 06:13:30.731647') ON CONFLICT (id) DO NOTHING;
INSERT INTO loading_bays (id, facility_id, name, code, status, created_at) VALUES ('BAY-02', 'FAC-001', 'Loading Bay 02', 'BAY-02-IMP', 'Monitoring', '2026-09-09 06:13:30.732647') ON CONFLICT (id) DO NOTHING;
INSERT INTO loading_bays (id, facility_id, name, code, status, created_at) VALUES ('BAY-03', 'FAC-001', 'Loading Bay 03', 'BAY-03-STG', 'Operational', '2026-09-09 06:13:30.733396') ON CONFLICT (id) DO NOTHING;
INSERT INTO loading_bays (id, facility_id, name, code, status, created_at) VALUES ('BAY-04', 'FAC-001', 'Loading Bay 04', 'BAY-04-HEV', 'Maintenance', '2026-09-09 06:13:30.734187') ON CONFLICT (id) DO NOTHING;
INSERT INTO loading_bays (id, facility_id, name, code, status, created_at) VALUES ('BAY-05', 'FAC-002', 'Loading Bay 05', 'BAY-05-MUM', 'Operational', '2026-09-09 06:13:30.734983') ON CONFLICT (id) DO NOTHING;
INSERT INTO loading_bays (id, facility_id, name, code, status, created_at) VALUES ('BAY-06', 'FAC-002', 'Loading Bay 06', 'BAY-06-MUM', 'Monitoring', '2026-09-09 06:13:30.735826') ON CONFLICT (id) DO NOTHING;

-- Ingesting 6 records into cameras
INSERT INTO cameras (id, loading_bay_id, name, camera_code, source_type, stream_url, status, last_seen_at, created_at) VALUES ('CAM-01', 'BAY-01', 'Camera 01 - Dock Overhead', 'CAM-01-HD', 'LIVE_STREAM', 'rtsp://stream.wms-intel.io/cam-01', 'ONLINE', '2026-09-09 06:13:30.747368', '2026-09-09 06:13:30.753455') ON CONFLICT (id) DO NOTHING;
INSERT INTO cameras (id, loading_bay_id, name, camera_code, source_type, stream_url, status, last_seen_at, created_at) VALUES ('CAM-02', 'BAY-02', 'Camera 02 - Ramp Angle', 'CAM-02-HD', 'LIVE_STREAM', 'rtsp://stream.wms-intel.io/cam-02', 'ONLINE', '2026-09-09 06:13:30.748303', '2026-09-09 06:13:30.753459') ON CONFLICT (id) DO NOTHING;
INSERT INTO cameras (id, loading_bay_id, name, camera_code, source_type, stream_url, status, last_seen_at, created_at) VALUES ('CAM-03', 'BAY-03', 'Camera 03 - Staging Area', 'CAM-03-HD', 'LIVE_STREAM', 'rtsp://stream.wms-intel.io/cam-03', 'DEGRADED', '2026-09-09 06:13:30.749263', '2026-09-09 06:13:30.753461') ON CONFLICT (id) DO NOTHING;
INSERT INTO cameras (id, loading_bay_id, name, camera_code, source_type, stream_url, status, last_seen_at, created_at) VALUES ('CAM-04', 'BAY-04', 'Camera 04 - Heavy Loading', 'CAM-04-HD', 'LIVE_STREAM', 'rtsp://stream.wms-intel.io/cam-04', 'OFFLINE', '2026-09-09 06:13:30.750264', '2026-09-09 06:13:30.753463') ON CONFLICT (id) DO NOTHING;
INSERT INTO cameras (id, loading_bay_id, name, camera_code, source_type, stream_url, status, last_seen_at, created_at) VALUES ('CAM-05', 'BAY-05', 'Camera 05 - Mumbai Dock A', 'CAM-05-HD', 'LIVE_STREAM', 'rtsp://stream.wms-intel.io/cam-05', 'ONLINE', '2026-09-09 06:13:30.751329', '2026-09-09 06:13:30.753465') ON CONFLICT (id) DO NOTHING;
INSERT INTO cameras (id, loading_bay_id, name, camera_code, source_type, stream_url, status, last_seen_at, created_at) VALUES ('CAM-06', 'BAY-06', 'Camera 06 - Mumbai Dock B', 'CAM-06-HD', 'LIVE_STREAM', 'rtsp://stream.wms-intel.io/cam-06', 'ONLINE', '2026-09-09 06:13:30.752431', '2026-09-09 06:13:30.753467') ON CONFLICT (id) DO NOTHING;

-- Ingesting 4 records into safety_rules
INSERT INTO safety_rules (id, facility_id, name, description, behaviour_type, threshold_config_json, risk_level, enabled, created_at, updated_at) VALUES ('RULE-001', 'FAC-001', 'Freedrop Height Detection', 'Triggers alert if carton drop height exceeds 0.8m with ground impact profile.', 'Product Dropped', '{"height_threshold_m": 0.8, "min_confidence": 0.85}', 'Critical', 1, '2026-09-09 06:13:30.764507', '2026-09-09 06:13:30.769073') ON CONFLICT (id) DO NOTHING;
INSERT INTO safety_rules (id, facility_id, name, description, behaviour_type, threshold_config_json, risk_level, enabled, created_at, updated_at) VALUES ('RULE-002', 'FAC-001', 'Forceful Dragging Violation', 'Detects friction abrasion dragging without dolly or mechanical assistance.', 'Product Dragged', '{"duration_seconds_threshold": 2.5, "min_confidence": 0.8}', 'Medium', 1, '2026-09-09 06:13:30.765632', '2026-09-09 06:13:30.769078') ON CONFLICT (id) DO NOTHING;
INSERT INTO safety_rules (id, facility_id, name, description, behaviour_type, threshold_config_json, risk_level, enabled, created_at, updated_at) VALUES ('RULE-003', 'FAC-001', 'Heavy-on-Fragile Stacking', 'Alerts when heavy cargo (>15kg) is stacked on fragile items.', 'Improper Stacking', '{"max_overhang_percent": 25, "weight_ratio_limit": 1.5}', 'High', 1, '2026-09-09 06:13:30.766693', '2026-09-09 06:13:30.769080') ON CONFLICT (id) DO NOTHING;
INSERT INTO safety_rules (id, facility_id, name, description, behaviour_type, threshold_config_json, risk_level, enabled, created_at, updated_at) VALUES ('RULE-004', 'FAC-001', 'Conveyor Velocity Spike', 'Flags sudden horizontal throwing/acceleration across roller belts.', 'Rough Handling', '{"max_accel_m_s2": 4.0, "min_confidence": 0.82}', 'High', 1, '2026-09-09 06:13:30.767819', '2026-09-09 06:13:30.769082') ON CONFLICT (id) DO NOTHING;

-- Ingesting 10 records into videos
INSERT INTO videos (video_id, camera_id, uploaded_by_user_id, filename, storage_key, mime_type, frame_count, fps, width, height, duration, status, processed_at, created_at) VALUES ('vid-01', NULL, NULL, 'Rolling and dropping carton.mp4', NULL, 'video/mp4', 1800, 30.0, 1920, 1080, 60.0, 'processed', NULL, '2026-09-09 17:59:07.975268') ON CONFLICT (video_id) DO NOTHING;
INSERT INTO videos (video_id, camera_id, uploaded_by_user_id, filename, storage_key, mime_type, frame_count, fps, width, height, duration, status, processed_at, created_at) VALUES ('vid-02', NULL, NULL, 'Dock level, dragging cupboard.mp4', NULL, 'video/mp4', 1350, 30.0, 1920, 1080, 45.0, 'processed', NULL, '2026-09-09 17:59:07.975273') ON CONFLICT (video_id) DO NOTHING;
INSERT INTO videos (video_id, camera_id, uploaded_by_user_id, filename, storage_key, mime_type, frame_count, fps, width, height, duration, status, processed_at, created_at) VALUES ('vid-03', NULL, NULL, 'KD packets dragged, heavy box kept on other packets.mp4', NULL, 'video/mp4', 1440, 30.0, 1920, 1080, 48.0, 'processed', NULL, '2026-09-09 17:59:07.975275') ON CONFLICT (video_id) DO NOTHING;
INSERT INTO videos (video_id, camera_id, uploaded_by_user_id, filename, storage_key, mime_type, frame_count, fps, width, height, duration, status, processed_at, created_at) VALUES ('vid-04', NULL, NULL, 'Throwing Mattresses.mp4', NULL, 'video/mp4', 1200, 30.0, 1920, 1080, 40.0, 'processed', NULL, '2026-09-09 17:59:07.975276') ON CONFLICT (video_id) DO NOTHING;
INSERT INTO videos (video_id, camera_id, uploaded_by_user_id, filename, storage_key, mime_type, frame_count, fps, width, height, duration, status, processed_at, created_at) VALUES ('vid-05', NULL, NULL, 'Stepping on cartons, vertical product kept horizontally, heavy product kept on top.mp4', NULL, 'video/mp4', 1050, 30.0, 1920, 1080, 35.0, 'processed', NULL, '2026-09-09 17:59:07.975277') ON CONFLICT (video_id) DO NOTHING;
INSERT INTO videos (video_id, camera_id, uploaded_by_user_id, filename, storage_key, mime_type, frame_count, fps, width, height, duration, status, processed_at, created_at) VALUES ('vid-06', NULL, NULL, 'Throwing seating cartons, using strap to hold.mp4', NULL, 'video/mp4', 1260, 30.0, 1920, 1080, 42.0, 'processed', NULL, '2026-09-09 17:59:07.975278') ON CONFLICT (video_id) DO NOTHING;
INSERT INTO videos (video_id, camera_id, uploaded_by_user_id, filename, storage_key, mime_type, frame_count, fps, width, height, duration, status, processed_at, created_at) VALUES ('vid-07', NULL, NULL, 'Rolling and dragging on wet floor.mp4', NULL, 'video/mp4', 900, 30.0, 1920, 1080, 30.0, 'processed', NULL, '2026-09-09 17:59:07.975279') ON CONFLICT (video_id) DO NOTHING;
INSERT INTO videos (video_id, camera_id, uploaded_by_user_id, filename, storage_key, mime_type, frame_count, fps, width, height, duration, status, processed_at, created_at) VALUES ('vid-cam01-20231027', 'CAM-01', NULL, 'Rolling and dropping carton.mp4', NULL, 'video/mp4', 0, 30.0, 1920, 1080, 60.0, 'COMPLETED', NULL, '2026-09-09 17:59:45.848082') ON CONFLICT (video_id) DO NOTHING;
INSERT INTO videos (video_id, camera_id, uploaded_by_user_id, filename, storage_key, mime_type, frame_count, fps, width, height, duration, status, processed_at, created_at) VALUES ('vid-cam02-20231027', 'CAM-02', NULL, 'loading_bay2_shift1.mp4', NULL, 'video/mp4', 0, 30.0, 1920, 1080, 120.0, 'COMPLETED', NULL, '2026-09-09 17:59:45.848947') ON CONFLICT (video_id) DO NOTHING;
INSERT INTO videos (video_id, camera_id, uploaded_by_user_id, filename, storage_key, mime_type, frame_count, fps, width, height, duration, status, processed_at, created_at) VALUES ('vid-cam03-20231028', 'CAM-03', NULL, 'aisle_staging_bay1.mp4', NULL, 'video/mp4', 0, 30.0, 1920, 1080, 90.0, 'COMPLETED', NULL, '2026-09-09 17:59:45.849579') ON CONFLICT (video_id) DO NOTHING;

-- Ingesting 43 records into events
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-001', NULL, 'FAC-001', 'vid-01', 1788976267.9648266, 'CAM-01', 'Loading Bay 01', NULL, 'Product Dropped / Freefall Impact', 94.6, 'Critical', 'Carton dropped from 1.4m height with vertical acceleration deceleration spike (>16.2 m/s²) upon ground impact.', 'CRITICAL RISK (94.6/100): Freefall deceleration exceeding 15.0 m/s² causes severe internal product fracturing, hidden component failure, and corrugated carton bursting.', NULL, NULL, '/videos/Rolling%20and%20dropping%20carton.mp4#t=03.2', '/videos/Rolling%20and%20dropping%20carton.mp4#t=03.2', 'Halt unloading sequence, inspect package corners for hidden structural compromise, and enforce two-handed placement.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 3.2, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985922', '2026-09-09 17:59:07.985926', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-002', NULL, 'FAC-001', 'vid-02', 1788975907.9648266, 'CAM-02', 'Loading Bay 02', NULL, 'Dragging Cartons or Cupboards on Floor', 82.5, 'High', 'Wooden cupboard unit dragged across warehouse concrete floor over 4.2m distance without trolley or pallet jack.', 'HIGH RISK (82.5/100): Continuous ground friction abrades bottom corrugated seals, tears packaging plies, and introduces ground moisture.', NULL, NULL, '/videos/Dock%20level%2C%20dragging%20cupboard.mp4#t=12.5', '/videos/Dock%20level%2C%20dragging%20cupboard.mp4#t=12.5', 'Provide hydraulic pallet truck or team-lift assistance. Strictly prohibit manual dragging across warehouse bays.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 12.5, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985927', '2026-09-09 17:59:07.985928', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-003', NULL, 'FAC-001', 'vid-03', 1788975427.9648266, 'CAM-04', 'Loading Bay 04', NULL, 'Improper Stacking Hierarchy (Heavy on Light)', 78.4, 'High', 'Heavy structural wooden box (approx 38kg) placed atop fragile corrugated KD packet packaging tier.', 'HIGH RISK (78.4/100): Inverted load distribution crushes lower box tiers, causing structural stack destabilization and dock tipping hazard.', NULL, NULL, '/videos/KD%20packets%20dragged%2C%20heavy%20box%20kept%20on%20other%20packets.mp4#t=14.8', '/videos/KD%20packets%20dragged%2C%20heavy%20box%20kept%20on%20other%20packets.mp4#t=14.8', 'Restructure pallet stack: place heaviest KD packets and cartons on the base tier with lighter goods above.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 14.8, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985930', '2026-09-09 17:59:07.985931', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-004', NULL, 'FAC-001', 'vid-04', 1788974887.9648266, 'CAM-05', 'Loading Bay 05', NULL, 'Throwing or Rolling Cartons / Mattresses', 92.4, 'Critical', 'Mattress unit launched airborne over 2.6m distance, tumbling onto loading bay floor with high momentum impact.', 'CRITICAL RISK (92.4/100): Uncontrolled airborne momentum transfer causes severe seam tearing, internal coil deformation, and worker struck-by hazard.', NULL, NULL, '/videos/Throwing%20Mattresses.mp4#t=04.8', '/videos/Throwing%20Mattresses.mp4#t=04.8', 'Dispatch shift supervisor to coach operator on controlled hand-off placement. Tag unit for quality check prior to storage.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 4.8, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985933', '2026-09-09 17:59:07.985933', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-005', NULL, 'FAC-001', 'vid-05', 1788974467.9648266, 'CAM-06', 'Loading Bay 06', NULL, 'Stepping or Standing on Cartons', 89.2, 'Critical', 'Warehouse operator standing directly atop product carton stack to reach upper rack, exerting >75kg concentrated point load.', 'CRITICAL RISK (89.2/100): Point load directly exceeds corrugated edge-crush limits, puncturing carton top and creating severe worker fall risk.', NULL, NULL, '/videos/Stepping%20on%20cartons%2C%20vertical%20product%20kept%20horizontally%2C%20heavy%20product%20kept%20on%20top.mp4#t=05.6', '/videos/Stepping%20on%20cartons%2C%20vertical%20product%20kept%20horizontally%2C%20heavy%20product%20kept%20on%20top.mp4#t=05.6', 'Immediately instruct operator to step off carton; maintain clear designated walking lanes and use certified stepladders at all times.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 5.6, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985935', '2026-09-09 17:59:07.985936', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-006', NULL, 'FAC-001', 'vid-06', 1788974047.9648266, 'CAM-03', 'Loading Bay 03', NULL, 'Using Packaging Straps as Lifting Handles', 58.0, 'Medium', 'Operator lifting heavy furniture parcel by its plastic polypropylene securing strap instead of designated cut-out hand-holes.', 'MEDIUM RISK (58.0/100): Plastic binding straps are not rated for dynamic hoisting and can snap under tension, dropping the load suddenly.', NULL, NULL, '/videos/Throwing%20seating%20cartons%2C%20using%20strap%20to%20hold.mp4#t=06.2', '/videos/Throwing%20seating%20cartons%2C%20using%20strap%20to%20hold.mp4#t=06.2', 'Instruct operator to use designated cut-out hand-holes or mechanical lifting aids. Replace sheared strapping.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 6.2, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985937', '2026-09-09 17:59:07.985938', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-007', NULL, 'FAC-001', 'vid-03', 1788973567.9648266, 'CAM-04', 'Loading Bay 04', NULL, 'Unstable Stacking & Pallet Overhang', 74.0, 'High', 'Cartons protruding 16cm beyond pallet boundary edges without interlocking stack pattern or stretch wrapping.', 'HIGH RISK (74.0/100): Overhanging package edges catch on dock door frames and passing forklift masts, causing total pallet load spill.', NULL, NULL, '/videos/KD%20packets%20dragged%2C%20heavy%20box%20kept%20on%20other%20packets.mp4#t=19.4', '/videos/KD%20packets%20dragged%2C%20heavy%20box%20kept%20on%20other%20packets.mp4#t=19.4', 'Re-align boxes flush with pallet footprint; apply minimum 4 layers of stretch film wrap before forklift transit.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 19.4, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985940', '2026-09-09 17:59:07.985941', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-008', NULL, 'FAC-001', 'vid-05', 1788973027.9648266, 'CAM-06', 'Loading Bay 06', NULL, 'Off-Orientation Placement (Vertical Stored Horizontally)', 54.0, 'Medium', 'Carton marked ''THIS SIDE UP'' with vertical orientation arrows positioned on its lateral side on storage floor.', 'MEDIUM RISK (54.0/100): Inverted orientation voids engineered shock-dampening foam suspension and stresses lateral carton joints.', NULL, NULL, '/videos/Stepping%20on%20cartons%2C%20vertical%20product%20kept%20horizontally%2C%20heavy%20product%20kept%20on%20top.mp4#t=08.4', '/videos/Stepping%20on%20cartons%2C%20vertical%20product%20kept%20horizontally%2C%20heavy%20product%20kept%20on%20top.mp4#t=08.4', 'Rotate carton immediately to upright vertical orientation matching directional arrows before bay departure.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 8.4, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985942', '2026-09-09 17:59:07.985943', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-009', NULL, 'FAC-001', 'vid-07', 1788972307.9648266, 'CAM-01', 'Loading Bay 01', NULL, 'Rough Handling & Excessive Impulse Acceleration', 76.5, 'High', 'Rapid, abrupt shove of carton across damp dock threshold resulting in severe impact deceleration spike against buffer wall.', 'HIGH RISK (76.5/100): High-impulse collisions generate internal shock waves that damage internal fragile assemblies and crack brackets.', NULL, NULL, '/videos/Rolling%20and%20dragging%20on%20wet%20floor.mp4#t=07.2', '/videos/Rolling%20and%20dragging%20on%20wet%20floor.mp4#t=07.2', 'Enforce controlled deceleration speeds during staging and prohibit shove-gliding across wet floors.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 7.2, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985945', '2026-09-09 17:59:07.985945', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-010', NULL, 'FAC-001', 'vid-02', 1788971647.9648266, 'CAM-02', 'Loading Bay 02', NULL, 'Unsafe Loading & Unloading Sequence', 72.0, 'High', 'Removing bottom supporting cartons from container tier while upper heavy cargo remains suspended without bracing.', 'HIGH RISK (72.0/100): Creating negative draft overhangs inside the truck container risks sudden outward avalanche onto unloading operators.', NULL, NULL, '/videos/Dock%20level%2C%20dragging%20cupboard.mp4#t=16.0', '/videos/Dock%20level%2C%20dragging%20cupboard.mp4#t=16.0', 'Enforce step-down unloading hierarchy: always unload cargo tier-by-tier from top to bottom.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 16.0, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985947', '2026-09-09 17:59:07.985948', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-011', NULL, 'FAC-001', 'vid-01', 1788970987.9648266, 'CAM-01', 'Loading Bay 01', NULL, 'Product Dropped / Freefall Impact', 91.2, 'Critical', 'Secondary carton drop: package rolled off pallet edge and impacted dock leveler lip at 14.8 m/s².', 'CRITICAL RISK (91.2/100): Edge corner deformation recorded. High risk of concealed internal product puncture.', NULL, NULL, '/videos/Rolling%20and%20dropping%20carton.mp4#t=18.4', '/videos/Rolling%20and%20dropping%20carton.mp4#t=18.4', 'Inspect packaging corner seams. Re-train operator on two-person lift for bulky KD parcels.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 18.4, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985949', '2026-09-09 17:59:07.985950', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-012', NULL, 'FAC-001', 'vid-02', 1788970147.9648266, 'CAM-02', 'Loading Bay 02', NULL, 'Dragging Cartons or Cupboards on Floor', 79.0, 'High', 'Cupboard dragged horizontally over dock transition plate with continuous floor contact.', 'HIGH RISK (79.0/100): Excessive base wear compromises cardboard moisture barrier.', NULL, NULL, '/videos/Dock%20level%2C%20dragging%20cupboard.mp4#t=24.5', '/videos/Dock%20level%2C%20dragging%20cupboard.mp4#t=24.5', 'Provide motorized pallet truck; prohibit unassisted manual dragging.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 24.5, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985952', '2026-09-09 17:59:07.985952', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-013', NULL, 'FAC-001', 'vid-03', 1788969247.9648266, 'CAM-04', 'Loading Bay 04', NULL, 'Improper Stacking Hierarchy (Heavy on Light)', 84.0, 'High', 'Secondary column stack: 42kg KD box resting on unsupported corner of base tier parcel.', 'HIGH RISK (84.0/100): Eccentric top load causes lateral stack lean and imminent stack topple.', NULL, NULL, '/videos/KD%20packets%20dragged%2C%20heavy%20box%20kept%20on%20other%20packets.mp4#t=31.0', '/videos/KD%20packets%20dragged%2C%20heavy%20box%20kept%20on%20other%20packets.mp4#t=31.0', 'De-stack pallet immediately. Place heavy KD cartons on base tier.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 31.0, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985954', '2026-09-09 17:59:07.985955', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-014', NULL, 'FAC-001', 'vid-04', 1788968347.9648266, 'CAM-05', 'Loading Bay 05', NULL, 'Throwing or Rolling Cartons / Mattresses', 90.5, 'Critical', 'Second mattress parcel tossed from vehicle interior onto dock staging ramp.', 'CRITICAL RISK (90.5/100): Impact shock compresses internal edge wire framing and creates worker hazards.', NULL, NULL, '/videos/Throwing%20Mattresses.mp4#t=12.0', '/videos/Throwing%20Mattresses.mp4#t=12.0', 'Coach operators on hand-to-hand controlled transfer. Discontinue throwing practices.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 12.0, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985956', '2026-09-09 17:59:07.985957', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-015', NULL, 'FAC-001', 'vid-06', 1788967447.9648266, 'CAM-03', 'Loading Bay 03', NULL, 'Using Packaging Straps as Lifting Handles', 62.0, 'Medium', 'Seating carton hoisted into sorting lane via single polypropylene strap.', 'MEDIUM RISK (62.0/100): Strap edge pressure cuts into carton lip and poses snap hazard.', NULL, NULL, '/videos/Throwing%20seating%20cartons%2C%20using%20strap%20to%20hold.mp4#t=18.5', '/videos/Throwing%20seating%20cartons%2C%20using%20strap%20to%20hold.mp4#t=18.5', 'Instruct operators to lift from base with two hands.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 18.5, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985959', '2026-09-09 17:59:07.985960', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-016', NULL, 'FAC-001', 'vid-05', 1788966667.9648266, 'CAM-06', 'Loading Bay 06', NULL, 'Stepping or Standing on Cartons', 88.0, 'Critical', 'Operator climbing over staged cartons to adjust overhead barcode scanner cable.', 'CRITICAL RISK (88.0/100): Dynamic footwear point load punctures carton lid and compromises fragile electronics inside.', NULL, NULL, '/videos/Stepping%20on%20cartons%2C%20vertical%20product%20kept%20horizontally%2C%20heavy%20product%20kept%20on%20top.mp4#t=18.2', '/videos/Stepping%20on%20cartons%2C%20vertical%20product%20kept%20horizontally%2C%20heavy%20product%20kept%20on%20top.mp4#t=18.2', 'Lock out climbing zone; require standard OSHA safety rolling ladder for rack maintenance.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 18.2, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985961', '2026-09-09 17:59:07.985962', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-017', NULL, 'FAC-001', 'vid-02', 1788965827.9648266, 'CAM-02', 'Loading Bay 02', NULL, 'Unsafe Loading & Unloading Sequence', 75.0, 'High', 'Unbraced vertical wooden cupboard removed while adjacent heavy furniture panel tilts forward.', 'HIGH RISK (75.0/100): Uncontrolled center-of-gravity shift poses crush hazard to unloading dock workers.', NULL, NULL, '/videos/Dock%20level%2C%20dragging%20cupboard.mp4#t=28.4', '/videos/Dock%20level%2C%20dragging%20cupboard.mp4#t=28.4', 'Deploy safety restraint bars before removing individual pieces from multi-panel shipping tiers.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 28.4, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985963', '2026-09-09 17:59:07.985964', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-018', NULL, 'FAC-001', 'vid-05', 1788965047.9648266, 'CAM-06', 'Loading Bay 06', NULL, 'Off-Orientation Placement (Vertical Stored Horizontally)', 56.0, 'Medium', 'Vertical wardrobe package stacked horizontally underneath heavy storage crate.', 'MEDIUM RISK (56.0/100): Lateral compression on unreinforced side walls risks pane rupture.', NULL, NULL, '/videos/Stepping%20on%20cartons%2C%20vertical%20product%20kept%20horizontally%2C%20heavy%20product%20kept%20on%20top.mp4#t=24.0', '/videos/Stepping%20on%20cartons%2C%20vertical%20product%20kept%20horizontally%2C%20heavy%20product%20kept%20on%20top.mp4#t=24.0', 'Restack immediately according to directional arrow indicators.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 24.0, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985966', '2026-09-09 17:59:07.985967', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-019', NULL, 'FAC-001', 'vid-07', 1788964147.9648266, 'CAM-01', 'Loading Bay 01', NULL, 'Rough Handling & Excessive Impulse Acceleration', 78.0, 'High', 'Carton accelerated forcefully across wet floor, skidding into metal dock guide rails.', 'HIGH RISK (78.0/100): High-speed wet surface skid terminates in metal barrier impact, damaging internal components.', NULL, NULL, '/videos/Rolling%20and%20dragging%20on%20wet%20floor.mp4#t=14.5', '/videos/Rolling%20and%20dragging%20on%20wet%20floor.mp4#t=14.5', 'Halt slip-sliding across floor; clean dock floor surface and use manual push-cart.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 14.5, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985968', '2026-09-09 17:59:07.985969', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-020', NULL, 'FAC-001', 'vid-03', 1788963247.9648266, 'CAM-04', 'Loading Bay 04', NULL, 'Unstable Stacking & Pallet Overhang', 76.0, 'High', 'Top-heavy KD packet stack leaning 14 degrees with 18cm overhang past pallet perimeter.', 'HIGH RISK (76.0/100): Severe overhang exceeds pallet boundary safety tolerance by >50%.', NULL, NULL, '/videos/KD%20packets%20dragged%2C%20heavy%20box%20kept%20on%20other%20packets.mp4#t=26.0', '/videos/KD%20packets%20dragged%2C%20heavy%20box%20kept%20on%20other%20packets.mp4#t=26.0', 'Re-palletize using interlocking column pattern and secure with strap bands.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.94, 'REAL_INFERENCE', 'PRODUCTION_PROTOTYPE', 0, 0, NULL, NULL, NULL, NULL, 30.0, 26.0, NULL, NULL, NULL, NULL, '2026-09-09 17:59:07.985970', '2026-09-09 17:59:07.985971', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-021', 'ORG-001', 'FAC-002', 'vid-cam06-20231029', 33.1, 'CAM-06', 'Loading Bay 06', 608, 'Improper Stacking', 64.0, 'High', 'Heavy machinery part stacked on top of cardboard carton box.', 'Inverted mass distribution profile detected by vision model.', NULL, NULL, '/videos/loading_bay2_shift1.mp4#t=33.1', '/videos/loading_bay2_shift1.mp4#t=33.1', 'Restack pallet immediately.', 'UNRESOLVED', NULL, NULL, 'YOLO11s', 'v1.4.2-tensorrt', 'LOCAL_YOLO11', 0.92, 'DEMO_FIXTURE', 'DEVELOPMENT', 0, 1, NULL, NULL, NULL, NULL, 30.0, NULL, NULL, NULL, NULL, NULL, '2026-09-09 17:59:45.863388', '2026-09-09 17:59:45.864840', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-DOCKL-001', 'ORG-001', 'FAC-001', 'vid-02', 12.5, 'CAM-01', 'Loading Bay 1', 182, 'product_dragged', 55.0, 'MEDIUM', 'Product dragged across floor: 104px horizontal distance over 0.80s at 130px/s.', 'MEDIUM RISK (55/100): Observed product dragged, combined with significant deceleration impact (6225px/s²), proximity to hazard area, repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 30.0, "duration_factor": 0.0, "frequency_factor": 15.0, "location_factor": 25.0}', '/api/videos/vid-02/frames/387', '/stream/video/Dock level, dragging cupboard.mp4#t=12.50', 'Check carton bases for friction abrasion or moisture. Instruct operators to use hand trolleys or pallet jacks rather than dragging on the floor.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.95, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-AC96DF6E', 'RA-F61F205C', 'OBS-24CE7350', 387, 30.0, 12.5, '2026-09-09 17:59:46.040367', 12.5, 13.3, NULL, '2026-09-09 17:59:46.040378', '2026-09-09 17:59:46.041421', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-DOCKL-002', 'ORG-001', 'FAC-001', 'vid-02', 12.5, 'CAM-01', 'Loading Bay 1', 182, 'equipment_violation', 41.0, 'MEDIUM', 'Equipment violation: large product (approx 248958px² area) manually handled over 255px without trolley or pallet jack.', 'MEDIUM RISK (41/100): Observed equipment violation, combined with proximity to hazard area, repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 0.0, "duration_factor": 7.8, "frequency_factor": 15.0, "location_factor": 25.0}', '/api/videos/vid-02/frames/409', '/stream/video/Dock level, dragging cupboard.mp4#t=12.50', 'Provide pallet jack or hand trolley for bulky furniture and KD packets. Prohibit manual dragging.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.82, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-AC96DF6E', 'RA-D36E3FE4', 'OBS-B05C7501', 409, 30.0, 12.5, '2026-09-09 17:59:46.056239', 12.5, 14.8, NULL, '2026-09-09 17:59:46.056249', '2026-09-09 17:59:46.056674', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-DOCKL-003', 'ORG-001', 'FAC-001', 'vid-02', 17.13, 'CAM-01', 'Loading Bay 1', 213, 'equipment_violation', 45.0, 'MEDIUM', 'Equipment violation: large product (approx 189259px² area) manually handled over 122px without trolley or pallet jack.', 'MEDIUM RISK (45/100): Observed equipment violation, combined with prolonged mishandling duration (5.1s), proximity to hazard area, repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 0.0, "duration_factor": 24.6, "frequency_factor": 15.0, "location_factor": 25.0}', '/api/videos/vid-02/frames/590', '/stream/video/Dock level, dragging cupboard.mp4#t=17.13', 'Provide pallet jack or hand trolley for bulky furniture and KD packets. Prohibit manual dragging.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.82, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-AC96DF6E', 'RA-0977DC53', 'OBS-2FCCB6C7', 590, 30.0, 17.13, '2026-09-09 17:59:46.067902', 17.13, 22.23, NULL, '2026-09-09 17:59:46.067919', '2026-09-09 17:59:46.068501', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-DOCKL-004', 'ORG-001', 'FAC-001', 'vid-02', 19.73, 'CAM-01', 'Loading Bay 1', 211, 'rough_handling', 62.0, 'HIGH', 'Rough handling detected: severe acceleration spike (8702px/s²) over 0.97s.', 'HIGH RISK (62/100): Observed rough handling, combined with significant deceleration impact (8702px/s²), proximity to hazard area. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 30.0, "duration_factor": 0.0, "frequency_factor": 0.0, "location_factor": 25.0}', '/api/videos/vid-02/frames/606', '/stream/video/Dock level, dragging cupboard.mp4#t=19.73', 'Examine package structural corners for crush damage. Conduct refresher briefing on controlled carton placement.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.75, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-AC96DF6E', 'RA-1D6C70A7', 'OBS-ED9539E9', 606, 30.0, 19.73, '2026-09-09 17:59:46.080129', 19.73, 20.7, NULL, '2026-09-09 17:59:46.080139', '2026-09-09 17:59:46.080480', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-DOCKL-005', 'ORG-001', 'FAC-001', 'vid-02', 19.9, 'CAM-01', 'Loading Bay 1', 213, 'product_dropped', 67.0, 'HIGH', 'Product dropped from height of 67px at 201px/s over 0.33s.', 'HIGH RISK (67/100): Observed product dropped, combined with significant deceleration impact (4030px/s²), proximity to hazard area. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.89, "impact_factor": 30.0, "duration_factor": 0.0, "frequency_factor": 0.0, "location_factor": 25.0}', '/api/videos/vid-02/frames/602', '/stream/video/Dock level, dragging cupboard.mp4#t=19.90', 'Physically inspect package seals and internal cushioning at evidence timestamp. Reinforce safe manual handling height limits with the shift team.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.8, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-AC96DF6E', 'RA-223DED20', 'OBS-F85FF401', 602, 30.0, 19.9, '2026-09-09 17:59:46.092086', 19.9, 20.23, NULL, '2026-09-09 17:59:46.092096', '2026-09-09 17:59:46.092486', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-DOCKL-006', 'ORG-001', 'FAC-001', 'vid-02', 20.1, 'CAM-01', 'Loading Bay 1', 213, 'product_dragged', 45.0, 'MEDIUM', 'Product dragged across floor: 76px horizontal distance over 1.43s at 53px/s.', 'MEDIUM RISK (45/100): Observed product dragged, combined with proximity to hazard area, repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 0.0, "duration_factor": 2.6, "frequency_factor": 15.0, "location_factor": 25.0}', '/api/videos/vid-02/frames/624', '/stream/video/Dock level, dragging cupboard.mp4#t=20.10', 'Check carton bases for friction abrasion or moisture. Instruct operators to use hand trolleys or pallet jacks rather than dragging on the floor.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.95, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-AC96DF6E', 'RA-CFFBC0E5', 'OBS-D5B19C1D', 624, 30.0, 20.1, '2026-09-09 17:59:46.104517', 20.1, 21.53, NULL, '2026-09-09 17:59:46.104528', '2026-09-09 17:59:46.104929', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-DOCKL-007', 'ORG-001', 'FAC-001', 'vid-02', 21.47, 'CAM-01', 'Loading Bay 1', 213, 'product_thrown', 68.0, 'HIGH', 'Product thrown / launched in air: traveled 99px at peak speed of 530px/s over 0.47s.', 'HIGH RISK (68/100): Observed product thrown, combined with proximity to hazard area. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 0.0, "duration_factor": 0.0, "frequency_factor": 7.5, "location_factor": 25.0}', '/api/videos/vid-02/frames/651', '/stream/video/Dock level, dragging cupboard.mp4#t=21.47', 'Halt unassisted tossing of items. Mandate two-person team lifts or conveyor transfer for cartons and mattresses.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.85, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-AC96DF6E', 'RA-C3DDEAE9', 'OBS-20AB76D3', 651, 30.0, 21.47, '2026-09-09 17:59:46.115688', 21.47, 21.93, NULL, '2026-09-09 17:59:46.115697', '2026-09-09 17:59:46.116046', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-DOCKL-008', 'ORG-001', 'FAC-001', 'vid-02', 22.47, 'CAM-01', 'Loading Bay 1', 272, 'product_thrown', 68.0, 'HIGH', 'Product thrown / launched in air: traveled 190px at peak speed of 356px/s over 1.07s.', 'HIGH RISK (68/100): Observed product thrown, combined with proximity to hazard area. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 0.0, "duration_factor": 0.4, "frequency_factor": 7.5, "location_factor": 25.0}', '/api/videos/vid-02/frames/690', '/stream/video/Dock level, dragging cupboard.mp4#t=22.47', 'Halt unassisted tossing of items. Mandate two-person team lifts or conveyor transfer for cartons and mattresses.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.85, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-AC96DF6E', 'RA-FC9C77E0', 'OBS-3F79D2DD', 690, 30.0, 22.47, '2026-09-09 17:59:46.127546', 22.47, 23.53, NULL, '2026-09-09 17:59:46.127557', '2026-09-09 17:59:46.127975', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-DOCKL-009', 'ORG-001', 'FAC-001', 'vid-02', 22.47, 'CAM-01', 'Loading Bay 1', 272, 'product_dragged', 57.0, 'MEDIUM', 'Product dragged across floor: 84px horizontal distance over 2.30s at 36px/s.', 'MEDIUM RISK (57/100): Observed product dragged, combined with significant deceleration impact (34445px/s²), proximity to hazard area, repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 30.0, "duration_factor": 7.8, "frequency_factor": 15.0, "location_factor": 25.0}', '/api/videos/vid-02/frames/708', '/stream/video/Dock level, dragging cupboard.mp4#t=22.47', 'Check carton bases for friction abrasion or moisture. Instruct operators to use hand trolleys or pallet jacks rather than dragging on the floor.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.95, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-AC96DF6E', 'RA-BC42887C', 'OBS-51C2EC1A', 708, 30.0, 22.47, '2026-09-09 17:59:46.139231', 22.47, 24.77, NULL, '2026-09-09 17:59:46.139242', '2026-09-09 17:59:46.139661', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-DOCKL-010', 'ORG-001', 'FAC-001', 'vid-02', 22.47, 'CAM-01', 'Loading Bay 1', 272, 'equipment_violation', 42.0, 'MEDIUM', 'Equipment violation: large product (approx 136894px² area) manually handled over 173px without trolley or pallet jack.', 'MEDIUM RISK (42/100): Observed equipment violation, combined with proximity to hazard area, repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 0.0, "duration_factor": 9.6, "frequency_factor": 15.0, "location_factor": 25.0}', '/api/videos/vid-02/frames/713', '/stream/video/Dock level, dragging cupboard.mp4#t=22.47', 'Provide pallet jack or hand trolley for bulky furniture and KD packets. Prohibit manual dragging.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.82, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-AC96DF6E', 'RA-343508F5', 'OBS-CD29FEC6', 713, 30.0, 22.47, '2026-09-09 17:59:46.151727', 22.47, 25.07, NULL, '2026-09-09 17:59:46.151740', '2026-09-09 17:59:46.152334', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-KDPAC-001', 'ORG-001', 'FAC-001', 'vid-03', 7.43, 'CAM-01', 'Loading Bay 2', 455, 'rough_handling', 64.0, 'HIGH', 'Rough handling detected: severe acceleration spike (22288px/s²), erratic zigzag trajectory over 0.47s.', 'HIGH RISK (64/100): Observed rough handling, combined with significant deceleration impact (11881px/s²), repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 30.0, "duration_factor": 8.2, "frequency_factor": 30.0, "location_factor": 0.0}', '/api/videos/vid-03/frames/258', '/stream/video/KD packets dragged, heavy box kept on other packets.mp4#t=7.43', 'Examine package structural corners for crush damage. Conduct refresher briefing on controlled carton placement.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.85, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-5FFD25B6', 'RA-5B9234A5', 'OBS-061EAFD3', 258, 30.0, 7.43, '2026-09-09 17:59:46.402098', 7.43, 9.8, NULL, '2026-09-09 17:59:46.402112', '2026-09-09 17:59:46.402677', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-KDPAC-002', 'ORG-001', 'FAC-001', 'vid-03', 7.53, 'CAM-01', 'Loading Bay 2', 455, 'product_thrown', 64.0, 'HIGH', 'Product thrown / launched in air: traveled 112px at peak speed of 1074px/s over 0.20s.', 'HIGH RISK (64/100): Observed product thrown, combined with repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 0.0, "duration_factor": 0.0, "frequency_factor": 22.5, "location_factor": 0.0}', '/api/videos/vid-03/frames/229', '/stream/video/KD packets dragged, heavy box kept on other packets.mp4#t=7.53', 'Halt unassisted tossing of items. Mandate two-person team lifts or conveyor transfer for cartons and mattresses.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.85, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-5FFD25B6', 'RA-EFD1463F', 'OBS-FD96BB64', 229, 30.0, 7.53, '2026-09-09 17:59:46.414526', 7.53, 7.73, NULL, '2026-09-09 17:59:46.414537', '2026-09-09 17:59:46.414984', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-KDPAC-003', 'ORG-001', 'FAC-001', 'vid-03', 13.27, 'CAM-01', 'Loading Bay 2', 525, 'product_thrown', 76.0, 'HIGH', 'Product thrown / launched in air: traveled 312px at peak speed of 1081px/s over 1.97s.', 'HIGH RISK (76/100): Observed product thrown, combined with significant deceleration impact (26899px/s²), repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 30.0, "duration_factor": 5.8, "frequency_factor": 22.5, "location_factor": 0.0}', '/api/videos/vid-03/frames/427', '/stream/video/KD packets dragged, heavy box kept on other packets.mp4#t=13.27', 'Halt unassisted tossing of items. Mandate two-person team lifts or conveyor transfer for cartons and mattresses.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.85, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-5FFD25B6', 'RA-8D02FB84', 'OBS-8BADF2C2', 427, 30.0, 13.27, '2026-09-09 17:59:46.426798', 13.27, 15.23, NULL, '2026-09-09 17:59:46.426819', '2026-09-09 17:59:46.427343', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-KDPAC-004', 'ORG-001', 'FAC-001', 'vid-03', 15.43, 'CAM-01', 'Loading Bay 2', 607, 'rough_handling', 62.0, 'HIGH', 'Rough handling detected: erratic zigzag trajectory over 0.53s.', 'HIGH RISK (62/100): Observed rough handling, combined with significant deceleration impact (19072px/s²), repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 30.0, "duration_factor": 0.0, "frequency_factor": 30.0, "location_factor": 0.0}', '/api/videos/vid-03/frames/471', '/stream/video/KD packets dragged, heavy box kept on other packets.mp4#t=15.43', 'Examine package structural corners for crush damage. Conduct refresher briefing on controlled carton placement.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.7, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-5FFD25B6', 'RA-6175BC38', 'OBS-0F2B0E05', 471, 30.0, 15.43, '2026-09-09 17:59:46.438295', 15.43, 15.97, NULL, '2026-09-09 17:59:46.438307', '2026-09-09 17:59:46.438719', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-KDPAC-005', 'ORG-001', 'FAC-001', 'vid-03', 21.1, 'CAM-01', 'Loading Bay 2', 607, 'rough_handling', 62.0, 'HIGH', 'Rough handling detected: severe acceleration spike (4704px/s²) over 0.47s.', 'HIGH RISK (62/100): Observed rough handling, combined with significant deceleration impact (4704px/s²), repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 30.0, "duration_factor": 0.0, "frequency_factor": 30.0, "location_factor": 0.0}', '/api/videos/vid-03/frames/640', '/stream/video/KD packets dragged, heavy box kept on other packets.mp4#t=21.10', 'Examine package structural corners for crush damage. Conduct refresher briefing on controlled carton placement.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.75, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-5FFD25B6', 'RA-14EBF2D6', 'OBS-C31D2AE8', 640, 30.0, 21.1, '2026-09-09 17:59:46.451141', 21.1, 21.57, NULL, '2026-09-09 17:59:46.451154', '2026-09-09 17:59:46.451727', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-KDPAC-006', 'ORG-001', 'FAC-001', 'vid-03', 23.5, 'CAM-01', 'Loading Bay 2', 607, 'rough_handling', 62.0, 'HIGH', 'Rough handling detected: erratic zigzag trajectory over 0.47s.', 'HIGH RISK (62/100): Observed rough handling, combined with significant deceleration impact (11537px/s²), repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 30.0, "duration_factor": 0.0, "frequency_factor": 30.0, "location_factor": 0.0}', '/api/videos/vid-03/frames/712', '/stream/video/KD packets dragged, heavy box kept on other packets.mp4#t=23.50', 'Examine package structural corners for crush damage. Conduct refresher briefing on controlled carton placement.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.7, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-5FFD25B6', 'RA-01288CBF', 'OBS-BBEC30EF', 712, 30.0, 23.5, '2026-09-09 17:59:46.462938', 23.5, 23.97, NULL, '2026-09-09 17:59:46.462949', '2026-09-09 17:59:46.463326', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-KDPAC-007', 'ORG-001', 'FAC-001', 'vid-03', 25.5, 'CAM-01', 'Loading Bay 2', 700, 'rough_handling', 62.0, 'HIGH', 'Rough handling detected: box rolling/tumbling, severe acceleration spike (6475px/s²), erratic zigzag trajectory over 0.83s.', 'HIGH RISK (62/100): Observed rough handling, combined with significant deceleration impact (6475px/s²), repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 30.0, "duration_factor": 0.0, "frequency_factor": 30.0, "location_factor": 0.0}', '/api/videos/vid-03/frames/777', '/stream/video/KD packets dragged, heavy box kept on other packets.mp4#t=25.50', 'Examine package structural corners for crush damage. Conduct refresher briefing on controlled carton placement.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.95, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-5FFD25B6', 'RA-720E887E', 'OBS-6C43B8A4', 777, 30.0, 25.5, '2026-09-09 17:59:46.475361', 25.5, 26.33, NULL, '2026-09-09 17:59:46.475371', '2026-09-09 17:59:46.475741', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-KDPAC-008', 'ORG-001', 'FAC-001', 'vid-03', 29.33, 'CAM-01', 'Loading Bay 2', 700, 'rough_handling', 62.0, 'HIGH', 'Rough handling detected: erratic zigzag trajectory over 0.57s.', 'HIGH RISK (62/100): Observed rough handling, combined with significant deceleration impact (17783px/s²), repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 30.0, "duration_factor": 0.0, "frequency_factor": 30.0, "location_factor": 0.0}', '/api/videos/vid-03/frames/888', '/stream/video/KD packets dragged, heavy box kept on other packets.mp4#t=29.33', 'Examine package structural corners for crush damage. Conduct refresher briefing on controlled carton placement.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.7, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-5FFD25B6', 'RA-75542848', 'OBS-D8E96B87', 888, 30.0, 29.33, '2026-09-09 17:59:46.486727', 29.33, 29.9, NULL, '2026-09-09 17:59:46.486739', '2026-09-09 17:59:46.487148', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-KDPAC-009', 'ORG-001', 'FAC-001', 'vid-03', 29.63, 'CAM-01', 'Loading Bay 2', 700, 'product_thrown', 64.0, 'HIGH', 'Product thrown / launched in air: traveled 99px at peak speed of 969px/s over 0.30s.', 'HIGH RISK (64/100): Observed product thrown, combined with repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 0.0, "duration_factor": 0.0, "frequency_factor": 22.5, "location_factor": 0.0}', '/api/videos/vid-03/frames/893', '/stream/video/KD packets dragged, heavy box kept on other packets.mp4#t=29.63', 'Halt unassisted tossing of items. Mandate two-person team lifts or conveyor transfer for cartons and mattresses.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.85, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-5FFD25B6', 'RA-83DD185F', 'OBS-0E5BFBB2', 893, 30.0, 29.63, '2026-09-09 17:59:46.496867', 29.63, 29.93, NULL, '2026-09-09 17:59:46.496877', '2026-09-09 17:59:46.497230', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-KDPAC-010', 'ORG-001', 'FAC-001', 'vid-03', 31.13, 'CAM-01', 'Loading Bay 2', 741, 'product_thrown', 64.0, 'HIGH', 'Product thrown / launched in air: traveled 97px at peak speed of 428px/s over 0.40s.', 'HIGH RISK (64/100): Observed product thrown, combined with repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 0.0, "duration_factor": 0.0, "frequency_factor": 22.5, "location_factor": 0.0}', '/api/videos/vid-03/frames/940', '/stream/video/KD packets dragged, heavy box kept on other packets.mp4#t=31.13', 'Halt unassisted tossing of items. Mandate two-person team lifts or conveyor transfer for cartons and mattresses.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.95, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-5FFD25B6', 'RA-D7CED272', 'OBS-E3269875', 940, 30.0, 31.13, '2026-09-09 17:59:46.510210', 31.13, 31.53, NULL, '2026-09-09 17:59:46.510220', '2026-09-09 17:59:46.510628', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-KDPAC-011', 'ORG-001', 'FAC-001', 'vid-03', 32.17, 'CAM-01', 'Loading Bay 2', 741, 'rough_handling', 62.0, 'HIGH', 'Rough handling detected: erratic zigzag trajectory over 0.47s.', 'HIGH RISK (62/100): Observed rough handling, combined with significant deceleration impact (10504px/s²), repeated handling violations in this session. Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 30.0, "duration_factor": 0.0, "frequency_factor": 30.0, "location_factor": 0.0}', '/api/videos/vid-03/frames/972', '/stream/video/KD packets dragged, heavy box kept on other packets.mp4#t=32.17', 'Examine package structural corners for crush damage. Conduct refresher briefing on controlled carton placement.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.7, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-5FFD25B6', 'RA-9E999017', 'OBS-33A71F3D', 972, 30.0, 32.17, '2026-09-09 17:59:46.522169', 32.17, 32.63, NULL, '2026-09-09 17:59:46.522178', '2026-09-09 17:59:46.522550', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
INSERT INTO events (event_id, organization_id, facility_id, video_id, timestamp, camera_id, bay_id, object_id, behaviour, risk_score, risk_level, description, reason, potential_consequence, risk_factors_json, evidence_frame, video_reference, recommended_action, status, acknowledged_by_user_id, acknowledged_at, model_name, model_version, inference_engine, confidence, provenance_type, environment, is_test_data, is_demo_data, inference_run_id, risk_assessment_id, behaviour_observation_id, frame_number, video_fps, timestamp_seconds, timestamp_utc, evidence_clip_start, evidence_clip_end, processing_latency_ms, created_at, updated_at, rule_version) VALUES ('EVT-THROWI-001', 'ORG-001', 'FAC-001', 'vid-06', 11.67, 'CAM-01', 'Loading Bay 1', 1691, 'rough_handling', 56.0, 'MEDIUM', 'Rough handling detected: box rolling/tumbling over 0.93s.', 'MEDIUM RISK (56/100): Observed rough handling, combined with significant deceleration impact (2761px/s²). Kinematic trajectory indicates potential handling risk to product integrity.', 'Potential inventory or operational safety risk.', '{"height_factor": 0.0, "impact_factor": 30.0, "duration_factor": 0.0, "frequency_factor": 0.0, "location_factor": 0.0}', '/api/videos/vid-06/frames/364', '/stream/video/Throwing seating cartons, using strap to hold.mp4#t=11.67', 'Examine package structural corners for crush damage. Conduct refresher briefing on controlled carton placement.', 'UNRESOLVED', NULL, NULL, 'best.pt', 'YOLO11s-Godrej', 'LOCAL_YOLO11', 0.8, 'REAL_INFERENCE', 'PRODUCTION', 0, 0, 'RUN-1206DF1B', 'RA-3D81D77D', 'OBS-B2262699', 364, 30.0, 11.67, '2026-09-09 17:59:47.175904', 11.67, 12.6, NULL, '2026-09-09 17:59:47.175922', '2026-09-09 17:59:47.176592', 'RULE-v1.0') ON CONFLICT (event_id) DO NOTHING;
