"""fix1_clean_indices

Revision ID: 86f933fb6f9c
Revises: 26b68d95a302
Create Date: 2026-09-09 10:38:28.065853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f933fb6f9c'
down_revision: Union[str, Sequence[str], None] = '26b68d95a302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_behaviour_observation_id'), ['behaviour_observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index('ix_events_facility_timestamp', ['facility_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_inference_run_id'), ['inference_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_is_demo_data'), ['is_demo_data'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_is_test_data'), ['is_test_data'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_provenance_type'), ['provenance_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_risk_assessment_id'), ['risk_assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)
        batch_op.create_index('ix_events_status_facility', ['status', 'facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_foreign_key(None, 'inference_runs', ['inference_run_id'], ['id'])
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])
        batch_op.create_foreign_key(None, 'behaviour_observations', ['behaviour_observation_id'], ['id'])
        batch_op.create_foreign_key(None, 'risk_assessments', ['risk_assessment_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['acknowledged_by_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'facilities', ['facility_id'], ['id'])
        batch_op.drop_column('rule_version')

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facilities_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('inference_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('model_sha256', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('finished_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_camera_id'), ['camera_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['uploaded_by_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'cameras', ['camera_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_videos_camera_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))

    with op.batch_alter_table('inference_runs', schema=None) as batch_op:
        batch_op.drop_column('finished_at')
        batch_op.drop_column('model_sha256')
        batch_op.drop_column('model_path')

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_facilities_organization_id'))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_version', sa.VARCHAR(), server_default=sa.text("'RULE-v1.0'"), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_events_timestamp'))
        batch_op.drop_index('ix_events_status_facility')
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_risk_assessment_id'))
        batch_op.drop_index(batch_op.f('ix_events_provenance_type'))
        batch_op.drop_index(batch_op.f('ix_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_events_is_test_data'))
        batch_op.drop_index(batch_op.f('ix_events_is_demo_data'))
        batch_op.drop_index(batch_op.f('ix_events_inference_run_id'))
        batch_op.drop_index('ix_events_facility_timestamp')
        batch_op.drop_index(batch_op.f('ix_events_facility_id'))
        batch_op.drop_index(batch_op.f('ix_events_environment'))
        batch_op.drop_index(batch_op.f('ix_events_behaviour_observation_id'))

    # ### end Alembic commands ###
